apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: eightball
  name: eightball-ui
  namespace: apps
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  resources:
    requests:
      memory: "500M"
      cpu: "100m"
    limits:
      memory: "750M"
      cpu: "1500m"
  source:
    git:
      url: https://github.com/sdeeg/eightball-ui.git
      ref:
        branch: main
